version: '3'

services:
  frontend:
    image: abhijjainn/sci-calc-frontend-image:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - sci-calc-network

  backend:
    image: abhijjainn/sci-calc-backend-image:latest
    ports:
      - "5000:5000"
    restart: always
    networks:
      - sci-calc-network
      
networks:
  sci-calc-network:
    driver: bridge